---
- assert:
    that:
    - akoi_config_path is defined
    - akoi_bin_path is defined
    - akoi_link_path is defined
    - akoi_tarball_is_removed is defined
    - akoi_working_dir is defined
    - akoi_version is defined
