---
# check link akoi_link_path
- name: check whether the link has already been installed
  stat:
    path: "{{akoi_link_path}}"
  register: stat_akoi_link_path
- block:
  - name: check akoi_link_path is symlink
    assert:
      that:
      - stat_akoi_link_path.stat.islnk
  - name: check whether the binary has already been installed
    stat:
      path: "{{stat_akoi_link_path.stat.lnk_source}}"
    register: stat_akoi_link_path_lnk_source
  - name: run akoi install
    shell: "{{akoi_link_path}} install -c {{akoi_config_path}} -f ansible 2>&1"
    register: result
    changed_when: (result.stdout|from_json)["changed"]
    when: stat_akoi_link_path_lnk_source.stat.exists and akoi_config_path is defined
  when: stat_akoi_link_path.stat.exists
- name: install akoi_bin_path
  import_tasks: install_akoi_bin_path.yml
  when: not stat_akoi_link_path.stat.exists or not stat_akoi_link_path_lnk_source.stat.exists
